version: '3'
services:
  mp4ru-service:
    build: .
    image: oxaoo/mp4ru-service:0.2.0
    container_name: mp4ru-service
    hostname: mp4ru-service
#        command: java -jar /opt/mp4ru/service/mp4ru-service-0.2.0.jar
    ports:
      - "2000:2000"
      - "2001:2001"